# Generated by Django 2.2.1 on 2019-05-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seonbi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
